version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: solid-tech
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=solid-investment.d19.tech
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=solid-investment.d19.tech
      - LETSENCRYPT_EMAIL=ovc@digit-it.ru
    volumes:
      - ${PWD}/conf.d/gzip.conf:/etc/nginx/conf.d/gzip.conf:ro
      - ${PWD}/public:/usr/share/nginx/html:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external:
      name: nginx-proxy